image: rays3t/sourcemod-plugins-builder-ci
build_core:
    stage: build
    script: 
    - spcomp
    - mkdir -p package/addons/sourcemod/plugins
    - mkdir -p package/addons/sourcemod/translations
    - mkdir -p package/addons/sourcemod/scripting/include
    - cp compiled/*.smx package/addons/sourcemod/plugins
    - cp *.sp package/addons/sourcemod/scripting
    - cp -r translations/* package/addons/sourcemod/translations
    - cp include/*.inc package/addons/sourcemod/scripting/include
    - cd package && rm -rf *.md
    artifacts:
        name: "${CI_PROJECT_NAME}_core_${CI_COMMIT_REF_NAME}"
        paths:
        - package/*
        
